#
# Module manifest for module 'IntunePowershellAPI'
#
# Generated by: Morten Reinhardtsen
#
# Generated on: 6/2/2017
#

@{

    # Script module or binary module file associated with this manifest
    RootModule        = '.\IntunePowershellAPI.psm1'

    # Version number of this module.
    ModuleVersion     = '0.1.0'

    # ID used to uniquely identify this module
    #GUID = ''

    # Author of this module
    Author            = 'Morten Reinhardtsen'

    # Company or vendor of this module
    CompanyName       = 'Ironstone IT'

    # Description of the functionality provided by this module
    Description       = 'This module provides a PowerShell wrapper for the Azure Graph API for Intune.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of the .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules     = 'Authentication\Get-MSGraphAuthenticationToken.ps1',
	'CompanyPortalBranding\CompanyPortal_Get.ps1',
	'CompliancePolicy\CompliancePolicy_Get.ps1',
	'DeviceConfiguration\DeviceConfiguration_Get.ps1',
	'Generic\Get-AzureADGroupAssignment.ps1',
	'Generic\Get-AzureADGroup.ps1',
	'Generic\Get-DeviceConfigurationPolicyAssignment.ps1',
	'Generic\Get-DeviceCompliancePolicyAssignment.ps1'
	
    # Functions to export from this module
    FunctionsToExport = 'Get-MSGraphAuthenticationToken',
	'Get-IntuneBrand',
	'Get-DeviceCompliancePolicy',
	'Get-DeviceConfigurationPolicy',
	'Get-DeviceCompliancePolicyAssignment',
	'Get-AADGroup',
	'Get-AzureADGroupAssignment',
	'Get-DeviceConfigurationPolicyAssignment',
	'Get-DeviceCompliancePolicyAssignment'

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport   = '*'

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    # PrivateData = ''

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}